Repository ArthuryanLoheac/ZAPPY, pull requests merged in 2025-06, with the labels that each got.

#99 🐛 Fix the main thread not used
  zappy_gui_src/main.cpp
Labels: bug

#97 🐛 Fix placement of the -LIrrlicht flag to be able to compile on clang
  Makefile
Labels: bug

#95 ✨ Upgrade the README for something more practical
  README.md
  docs/assets/trantor.png
Labels: documentation

#101 :sparkles: Egg management & updating tiles
  zappy_gui_src/Connection/Commands/CommandServer.cpp
  zappy_gui_src/Connection/ServerGUI.cpp
  zappy_gui_src/Connection/ServerGUI.hpp
  zappy_gui_src/DataManager/DataManager.cpp
  zappy_gui_src/DataManager/DataManager.hpp
  zappy_gui_src/DataManager/GameDataManager.cpp
  zappy_gui_src/DataManager/GameDataManager.hpp
  zappy_gui_src/DataManager/GameTile.cpp
  zappy_gui_src/DataManager/GameTile.hpp
  zappy_gui_src/Exceptions/ServerGUIExceptions.hpp
  zappy_gui_src/Graphic/Window/window.cpp
  zappy_gui_src/main.cpp
  zappy_gui_src/tools/MeshImporter.cpp
Labels: feature

#109 :sparkles: create common code for socket handling from x to the server
  Makefile
  lib/Socket/Socket.cpp
  lib/Socket/Socket.hpp
Labels: feature

#113 :bug: :memo: fix camera movement & documentation GUI
  docs/docs/zappy/GUI_PROTOCOL.md
  zappy_gui_src/Graphic/Window/WindowEvent.cpp
Labels: bug

#111 👷Fix deploy-doc CI
  .github/workflows/deploy_doc.yml
  CONTRIBUTING.md
  docs/.gitignore
  docs/docs/zappy/CONTRIBUTING.md
  docs/docusaurus.config.ts
  docs/package-lock.json
Labels: documentation

#116 🐛 fix segfault on number of team parsing
  zappy_server_src/include/parser.h
  zappy_server_src/include/zappy.h
  zappy_server_src/main.c
  zappy_server_src/map_creation.c
  zappy_server_src/parser.c
Labels: bug

#131 Standardize command exec on server
  tests/zappy_ai.sh
  tests/zappy_gui.sh
  tests/zappy_serv.sh
  zappy_server_src/execution_command/check_ticks.c
  zappy_server_src/execution_command/command_association_list.c
  zappy_server_src/execution_command/common.c
  zappy_server_src/execution_command/forward_command.c
  zappy_server_src/execution_command/get_command_handler.c
  zappy_server_src/execution_command/left_command.c
  zappy_server_src/execution_command/look_command.c
  zappy_server_src/execution_command/right_command.c
  zappy_server_src/include/command.h
  zappy_server_src/include/command_handler.h
Labels: feature

#136 :sparkles: handle look command
  zappy_server_src/client.c
  zappy_server_src/exec_command.c
  zappy_server_src/execution_command/check_ticks.c
  zappy_server_src/execution_command/forward_command.c
  zappy_server_src/execution_command/get_command_handler.c
  zappy_server_src/execution_command/look_command.c
  zappy_server_src/include/command_handler.h
  zappy_server_src/parser.c
Labels: feature

#142 :sparkles: fluid movements
  tests/zappy_gui.sh
  zappy_gui_src/DataManager/Player.cpp
  zappy_gui_src/DataManager/Player.hpp
Labels: feature

#145 Add inventory command to the ai
  zappy_ai_src/Data/Data.hpp
  zappy_ai_src/Interface/Interface.cpp
  zappy_ai_src/Interface/Interface.hpp
  zappy_ai_src/Interface/Inventory.cpp
  zappy_ai_src/main.cpp
Labels: feature

#150 ✨ 144 refactor the creation of commands
  README.md
  libc/logs.c
  tests/zappy_serv.sh
  zappy_server_src/client.c
  zappy_server_src/command.c
  zappy_server_src/command_parsing/commands_name_size.c
  zappy_server_src/command_parsing/extract_command.c
  zappy_server_src/command_parsing/get_command_duration.c
  zappy_server_src/command_parsing/process_command.c
  zappy_server_src/command_parsing/push_command_to_queue.c
  zappy_server_src/include/client.h
  zappy_server_src/include/command.h
  zappy_server_src/main.c
  zappy_server_src/parser.c
  zappy_server_src/zappy.c
Labels: feature

#148 :sparkles: take object command handling for the server
  zappy_server_src/execution_command/command_association_list.c
  zappy_server_src/execution_command/common.c
  zappy_server_src/execution_command/take_command.c
  zappy_server_src/include/command_handler.h
Labels: feature

#153 ✨ Set command handling for the server
  zappy_server_src/execution_command/command_association_list.c
  zappy_server_src/execution_command/set_command.c
  zappy_server_src/execution_command/take_command.c
  zappy_server_src/include/command.h
  zappy_server_src/include/command_handler.h
Labels: feature

#154 ♻️ separate players gui clients commands pools
  zappy_server_src/command_parsing/commands_name_size_lists.c
  zappy_server_src/command_parsing/get_command_duration.c
  zappy_server_src/command_parsing/push_command_to_queue.c
  zappy_server_src/include/command.h
Labels: feature

#138 📝 Doxygen added
  .github/workflows/deploy_doc.yml
  Makefile
  docs/Doxyfile
  docs/docusaurus.config.ts
  docs/generate-doxygen.sh
  docs/package.json
Labels: feature

#156 :sparkles: Improvement on visuals GUI
  .github/workflows/pain_au_chocolat.yml
  assets/Solid_BgUI.png
  docs/docs/zappy/CONTRIBUTING.md
  tests/zappy_gui.sh
  zappy_gui_src/DataManager/GameTile.cpp
  zappy_gui_src/DataManager/GameTile.hpp
  zappy_gui_src/DataManager/Player.cpp
  zappy_gui_src/DataManager/Player.hpp
  zappy_gui_src/Graphic/Events/MyEventReceiver.hpp
  zappy_gui_src/Graphic/Window/WindowEvent.cpp
  zappy_gui_src/Graphic/Window/window.cpp
  zappy_gui_src/Graphic/Window/window.hpp
  zappy_gui_src/Graphic/Window/windowUI.cpp
  zappy_server_src/client.c
Labels: feature

#158 ✨ Implement tick count and map update logic
  zappy_server_src/execution_command/check_ticks.c
  zappy_server_src/include/zappy.h
  zappy_server_src/map.c
  zappy_server_src/map_creation.c
  zappy_server_src/map_update.c
  zappy_server_src/zappy.c
Labels: feature

#161 :sparkles: handle death and ressource management for players
  Makefile
  zappy_gui_src/Graphic/Window/windowUI.cpp
  zappy_server_src/client.c
  zappy_server_src/command_parsing/process_command.c
  zappy_server_src/command_parsing/push_command_to_queue.c
  zappy_server_src/data_send/data_send_player.c
  zappy_server_src/execution_command/check_ticks.c
  zappy_server_src/execution_command/common.c
  zappy_server_src/execution_command/connect_nbr_command.c
  zappy_server_src/execution_command/forward_command.c
  zappy_server_src/execution_command/left_command.c
  zappy_server_src/execution_command/look_command.c
  zappy_server_src/execution_command/right_command.c
  zappy_server_src/execution_command/set_command.c
  zappy_server_src/execution_command/take_command.c
  zappy_server_src/include/client.h
  zappy_server_src/include/command_handler.h
Labels: feature

#162 ♻️ unify logs system
  Makefile
  README.md
  libc/include/logs.h
  libc/logs.c
  zappy_ai_src/main.cpp
  zappy_gui_src/Connection/ServerGUI.cpp
  zappy_gui_src/Connection/connectionWithServer.cpp
  zappy_gui_src/DataManager/DataManager.cpp
  zappy_gui_src/DataManager/DataManager.hpp
  zappy_gui_src/main.cpp
  zappy_server_src/parser.c
Labels: Feature

#170 ✨ gui commands handling
  tests/zappy_gui.sh
  zappy_server_src/execution_command/check_ticks.c
  zappy_server_src/execution_command/command_association_list.c
  zappy_server_src/execution_command/common.c
  zappy_server_src/execution_command/get_command_handler.c
  zappy_server_src/execution_command/gui/bct_command.c
  zappy_server_src/execution_command/gui/mct_command.c
  zappy_server_src/execution_command/gui/msz_command.c
  zappy_server_src/execution_command/gui/pin_command.c
  zappy_server_src/execution_command/gui/plv_command.c
  zappy_server_src/execution_command/gui/ppo_command.c
  zappy_server_src/execution_command/gui/sgt_command.c
  zappy_server_src/execution_command/gui/sst_command.c
  zappy_server_src/execution_command/gui/tna_command.c
  zappy_server_src/execution_command/player/connect_nbr_command.c
  zappy_server_src/execution_command/player/forward_command.c
  zappy_server_src/execution_command/player/left_command.c
  zappy_server_src/execution_command/player/look_command.c
  zappy_server_src/execution_command/player/right_command.c
  zappy_server_src/execution_command/player/set_command.c
  zappy_server_src/execution_command/player/take_command.c
  zappy_server_src/include/command_handler.h
Labels: Feature

#163 :sparkles: handle fork command
  zappy_server_src/execution_command/command_association_list.c
  zappy_server_src/execution_command/common.c
  zappy_server_src/execution_command/fork_command.c
  zappy_server_src/include/command_handler.h
  zappy_server_src/include/zappy.h
  zappy_server_src/map_creation.c
Labels: Feature

#181 :sparkles: eject command & fix delta time bug in UI
  zappy_ai_src/Connection/ServerAI.cpp
  zappy_gui_src/DataManager/Player.cpp
  zappy_gui_src/Graphic/Window/window.cpp
  zappy_gui_src/Graphic/Window/window.hpp
  zappy_gui_src/Graphic/Window/windowUI.cpp
  zappy_server_src/command_parsing/handle_incantation.c
  zappy_server_src/execution_command/command_association_list.c
  zappy_server_src/execution_command/player/eject_command.c
  zappy_server_src/execution_command/player/incantation_command.c
  zappy_server_src/include/command_handler.h
Labels: Feature

#185 :sparkles: Add documentation link to README
  README.md
Labels: Documentation, Feature

#187 :sparkles: Add AI Protocol documentation for client/server communication
  docs/docs/zappy/AI_PROTOCOL.md
Labels: Documentation

#183 :sparkles: Add Plugins system for UI management
  Makefile
  assets/UI/All.png
  docs/docs/zappy/PLUGIN_CREATION.md
  tests/zappy_gui.sh
  tests/zappy_serv.sh
  zappy_gui_plugins_src/PlayerDataPlugin.cpp
  zappy_gui_plugins_src/PlayerDataPlugin.hpp
  zappy_gui_plugins_src/TileDataPlugin.cpp
  zappy_gui_plugins_src/TileDataPlugin.hpp
  zappy_gui_plugins_src/globalDataPlugin.cpp
  zappy_gui_plugins_src/globalDataPlugin.hpp
  zappy_gui_src/DataManager/GameDataManager.cpp
  zappy_gui_src/Graphic/Events/MyEventReceiver.hpp
  zappy_gui_src/Graphic/Window/WindowEvent.cpp
  zappy_gui_src/Graphic/Window/window.cpp
  zappy_gui_src/Graphic/Window/window.hpp
  zappy_gui_src/Graphic/Window/windowUI.cpp
  zappy_gui_src/Graphic/graphic.cpp
  zappy_gui_src/PluginsManagement/PluginsDataManager.cpp
  zappy_gui_src/PluginsManagement/PluginsDataManager.hpp
  zappy_gui_src/PluginsManagement/pluginsData.hpp
  zappy_gui_src/PluginsManagement/pluginsInterface.hpp
  zappy_gui_src/PluginsManagement/pluginsManager.cpp
  zappy_gui_src/PluginsManagement/pluginsManager.hpp
  zappy_gui_src/dlLoader/dlLoader.hpp
  zappy_gui_src/tools/MeshImporter.hpp
Labels: Feature

#190 :bug: Fix server closing for no reason & add hello message
  Makefile
  tests/zappy_serv.sh
  zappy_server_src/command.c
  zappy_server_src/zappy.c
Labels: Bug

#191 :sparkles: Improve client disconnection handling and limit maximum co…
  zappy_server_src/command.c
  zappy_server_src/zappy.c
Labels: Feature

#195 :sparkles: Send disconnection message to graphics when a client disconnect
  zappy_server_src/command.c
Labels: Feature

#199 :sparkles: add soundeffects & musics
  Makefile
  assets/Musics/Ambient.mp3
  assets/Musics/Death.mp3
  assets/Musics/DeathEgg.wav
  assets/Musics/Drop.wav
  assets/Musics/Elevation.wav
  assets/Musics/Push.wav
  assets/Musics/Spawn.wav
  assets/Musics/SpawnEgg.wav
  assets/Musics/Take.wav
  tests/zappy_gui.sh
  zappy_gui_src/Connection/Commands/CommandServer.cpp
  zappy_gui_src/Connection/ServerGUI.hpp
  zappy_gui_src/DataManager/GameDataManager.cpp
  zappy_gui_src/DataManager/GameDataManager.hpp
  zappy_gui_src/DataManager/SoundsManager.cpp
  zappy_gui_src/DataManager/SoundsManager.hpp
  zappy_gui_src/Exceptions/SoundsManagerExceptions.hpp
  zappy_gui_src/Graphic/Window/window.cpp
  zappy_gui_src/Graphic/graphic.cpp
  zappy_server_src/command.c
  zappy_server_src/execution_command/player/set_command.c
  zappy_server_src/execution_command/player/take_command.c
Labels: Feature

#208 :sparkles: win condition
  zappy_server_src/execution_command/player/fork_command.c
  zappy_server_src/execution_command/player/incantation_command.c
  zappy_server_src/execution_command/win_condition.c
  zappy_server_src/include/command_handler.h
  zappy_server_src/include/zappy.h
  zappy_server_src/main.c
Labels: Feature

#205 ✨ Replaced throw by LOG and add verbose to the AI
  lib/Socket/Socket.hpp
  libcpp/Socket.cpp
  tests/zappy_serv.sh
  zappy_ai_src/Interface/Communication.cpp
  zappy_ai_src/Interface/Interaction.cpp
  zappy_ai_src/Interface/Interface.cpp
  zappy_ai_src/Interface/Inventory.cpp
  zappy_ai_src/Interface/Mouvement.cpp
  zappy_ai_src/Interface/Special.cpp
  zappy_ai_src/main.cpp
Labels: Feature

#217 ♻️ Refactor all mesh creation system
  zappy_gui_plugins_src/ConnectionStatePlugin.hpp
  zappy_gui_src/Connection/Commands/CommandServer.cpp
  zappy_gui_src/DataManager/Egg.cpp
  zappy_gui_src/DataManager/Egg.hpp
  zappy_gui_src/DataManager/GameDataManager.cpp
  zappy_gui_src/DataManager/GameDataManager.hpp
  zappy_gui_src/DataManager/GameTile.cpp
  zappy_gui_src/DataManager/Player.cpp
  zappy_gui_src/DataManager/Player.hpp
  zappy_gui_src/DataManager/PlayerGetSeter.cpp
  zappy_gui_src/Graphic/Window/window.cpp
  zappy_gui_src/Graphic/Window/window.hpp
Labels: Feature

#219 :bug: fix bugs with take and set
  zappy_server_src/execution_command/player/set_command.c
  zappy_server_src/execution_command/player/take_command.c
Labels: Bug

#221 :bug: fix the refactor problems of the gui
  tests/zappy_gui.sh
  tests/zappy_serv.sh
  zappy_gui_plugins_src/frequencyPlugin.cpp
  zappy_gui_src/Connection/Commands/CommandServer.cpp
  zappy_gui_src/DataManager/Egg.hpp
  zappy_gui_src/DataManager/GameDataManager.cpp
  zappy_gui_src/DataManager/GameTile.cpp
  zappy_gui_src/DataManager/GameTile.hpp
  zappy_gui_src/DataManager/Player.cpp
  zappy_gui_src/DataManager/Player.hpp
  zappy_gui_src/DataManager/PlayerGetSeter.cpp
  zappy_gui_src/Graphic/Window/window.cpp
  zappy_gui_src/Graphic/Window/window.hpp
  zappy_gui_src/Graphic/graphic.cpp
  zappy_gui_src/main.cpp
  zappy_server_src/command.c
  zappy_server_src/command_parsing/push_command_to_queue.c
Labels: Bug

#220 🐛 fix eject command
  libc/logs.c
  zappy_server_src/delete_egg.c
  zappy_server_src/execution_command/player/eject_command.c
  zappy_server_src/include/client.h
  zappy_server_src/include/zappy.h
  zappy_server_src/zappy.c
Labels: Bug

#229 🐛 Server can no longuer start with a frequency > 200
  zappy_server_src/parser.c
Labels: Bug

#232 :bug: fix broadcast error
  zappy_gui_plugins_src/MessagesPlugin.cpp
  zappy_server_src/execution_command/player/broadcast_command.c
Labels: Bug

#233 :sparkles: add command seg
  Makefile
  assets/UI/trophy.png
  zappy_gui_plugins_src/winnerPlugin.cpp
  zappy_gui_plugins_src/winnerPlugin.hpp
  zappy_gui_src/Connection/Commands/CommandServer.cpp
  zappy_gui_src/Connection/ServerGUI.cpp
  zappy_gui_src/Connection/ServerGUI.hpp
  zappy_gui_src/DataManager/GameDataManager.cpp
  zappy_gui_src/DataManager/GameDataManager.hpp
  zappy_gui_src/PluginsManagement/PluginsDataManager.cpp
  zappy_gui_src/PluginsManagement/pluginsData.hpp
  zappy_gui_src/PluginsManagement/pluginsManager.cpp
Labels: Feature

#238 ✨ Add kirby module
  zappy_ai_src/modules/KirbyModule.cpp
  zappy_ai_src/modules/KirbyModule.hpp
Labels: Feature

#245 :bug: unlock map size
  zappy_gui_plugins_src/graphRessourcesPlugin.cpp
  zappy_gui_plugins_src/graphRessourcesPlugin.hpp
  zappy_server_src/parser.c
Labels: Bug

#246 ✨ Add ConnectionStatePlugin_Water for showing animation 2d
  assets/UI/WaterLoading/1.png
  assets/UI/WaterLoading/10.png
  assets/UI/WaterLoading/2.png
  assets/UI/WaterLoading/3.png
  assets/UI/WaterLoading/4.png
  assets/UI/WaterLoading/5.png
  assets/UI/WaterLoading/6.png
  assets/UI/WaterLoading/7.png
  assets/UI/WaterLoading/8.png
  assets/UI/WaterLoading/9.png
  zappy_gui_plugins_src/ConnectionStatePlugin_Water.cpp
  zappy_gui_plugins_src/ConnectionStatePlugin_Water.hpp
Labels: Feature

#256 🚨 Fix compilation of zappy_gui & zappy_ai
  Makefile
  zappy_ai_src/modules/AdvancedLeveler.cpp
  zappy_ai_src/modules/AdvancedLeveler.hpp
Labels: Bug

#262 📝 Update README with installation instructions for irrlicht
  README.md
Labels: Bug

#260 ✨ Add inventory command
  zappy_server_src/execution_command/command_association_list.c
  zappy_server_src/execution_command/player/broadcast_command.c
  zappy_server_src/execution_command/player/connect_nbr_command.c
  zappy_server_src/execution_command/player/eject_command.c
  zappy_server_src/execution_command/player/fork_command.c
  zappy_server_src/execution_command/player/forward_command.c
  zappy_server_src/execution_command/player/incantation_command.c
  zappy_server_src/execution_command/player/inventory_command.c
  zappy_server_src/execution_command/player/left_command.c
  zappy_server_src/execution_command/player/look_command.c
  zappy_server_src/execution_command/player/right_command.c
  zappy_server_src/execution_command/player/set_command.c
  zappy_server_src/execution_command/player/take_command.c
  zappy_server_src/include/command_handler.h
Labels: Feature

#242 ✨ Update readme and docusarus website
  README.md
  docs/docusaurus.config.ts
  docs/src/pages/index.tsx
  zappy_ai_src/main.cpp
Labels: Documentation

#269 :sparkles: remove the irrlicht call command in the network part
  zappy_gui_src/Connection/Commands/CommandServer.cpp
  zappy_gui_src/Connection/ServerGUI.cpp
  zappy_gui_src/Connection/ServerGUI.hpp
  zappy_gui_src/Connection/connectionWithServer.cpp
  zappy_gui_src/Graphic/Window/window.cpp
  zappy_gui_src/Graphic/Window/window.hpp
  zappy_gui_src/Graphic/graphic.cpp
Labels: Feature

#268 ✨ Add write buffer
  lib/Socket/Socket.cpp
  libcpp/Socket.cpp
  libcpp/Socket/Socket.hpp
Labels: Feature

#272 :bug: Refactor buffer initialization and formatting in look_command
  zappy_server_src/execution_command/player/look_command.c
Labels: Bug

#275 ♻️ Server now stop sending and receving message after a team has won
  tests/zappy_serv.sh
  zappy_server_src/zappy.c
Labels: Feature

#287 ♻️ Refactor static struct to boolean for server shutdown handling
  zappy_server_src/include/zappy.h
  zappy_server_src/main.c
  zappy_server_src/zappy.c
Labels: Bug

#290 :saprkles: add Debug tile plugin
  zappy_gui_plugins_src/ConnectionStatePlugin_Water.hpp
  zappy_gui_plugins_src/TileDataPluginDebug.cpp
  zappy_gui_plugins_src/TileDataPluginDebug.hpp
  zappy_server_src/command.c
  zappy_server_src/command_parsing/commands_name_size_lists.c
  zappy_server_src/command_parsing/extract_command.c
  zappy_server_src/execution_command/command_association_list.c
  zappy_server_src/execution_command/gui/d_ressource_command.c
  zappy_server_src/include/command_handler.h
Labels: Feature

#285 🐛 Remove the hard coded write and check for close return value
  zappy_server_src/client.c
  zappy_server_src/zappy.c
Labels: Bug

#301 ✨ Improve player mesh handling and visibility management in various p…
  zappy_gui_plugins_src/MessagesPlugin.cpp
  zappy_gui_plugins_src/MessagesPlugin.hpp
  zappy_gui_plugins_src/PlayerDataPlugin.cpp
  zappy_gui_src/DataManager/PlayerGetSeter.cpp
  zappy_gui_src/Graphic/Window/window.cpp
  zappy_gui_src/PluginsManagement/pluginsData.hpp
Labels: Feature

#300 ✨ Add EJECT handling
  zappy_ai_src/Data/Data.hpp
  zappy_ai_src/Interface/Interaction.cpp
  zappy_ai_src/Interface/Interface.cpp
  zappy_ai_src/Interface/Interface.hpp
Labels: Feature

#308 📝 Remove ZIP ZOUP from docusaurus homepage
  docs/docusaurus.config.ts
  docs/src/pages/index.tsx
Labels: Documentation

#309 :memo: Doc protocol scale up
  docs/docs/zappy/GUI_PROTOCOL.md
  docs/docs/zappy/GUI_RFC.txt
  zappy_gui_src/Connection/Commands/CommandServer.cpp
  zappy_gui_src/DataManager/Player.hpp
  zappy_gui_src/tools/MeshImporter.cpp
Labels: Bug

#310 📝 Add -o to the -h & readme for the gui
  README.md
  zappy_gui_src/main.cpp
Labels: Documentation
